server:
  port: 8082

spring:
  application:
    name: product-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
  mongodb:
    uri: mongodb://root:password@localhost:27018/product-service-db?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: product_service.events.ImageUploadedEvent
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true