server:
  port: 8080   # make sure no other service uses 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

          discovery:
            locator:
              enabled: true

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**,/api/auth/**,/me
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
            - id: media-service
              uri: lb://MEDIA-SERVICE
              predicates:
                - Path=/media/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true